// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PPECheckoutSystem.Data;

#nullable disable

namespace PPECheckoutSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260719165018_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PPECheckoutSystem.Models.CheckoutRecord", b =>
                {
                    b.Property<int>("CheckoutRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckoutRecordId"));

                    b.Property<DateTime?>("CheckedInAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckedOutAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CheckoutNotes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ReturnCondition")
                        .HasColumnType("int");

                    b.Property<string>("ReturnNotes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("CheckoutRecordId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EquipmentItemId");

                    b.ToTable("CheckoutRecords");
                });

            modelBuilder.Entity("PPECheckoutSystem.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("BadgeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("BadgeNumber")
                        .IsUnique();

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PPECheckoutSystem.Models.EquipmentCategory", b =>
                {
                    b.Property<int>("EquipmentCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("DefaultCheckoutDays")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("EquipmentCategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("EquipmentCategories");

                    b.HasData(
                        new
                        {
                            EquipmentCategoryId = 1,
                            CategoryName = "Hard Hat",
                            DefaultCheckoutDays = 7,
                            Description = "Protective head equipment"
                        },
                        new
                        {
                            EquipmentCategoryId = 2,
                            CategoryName = "Safety Vest",
                            DefaultCheckoutDays = 7,
                            Description = "High-visibility safety vest"
                        },
                        new
                        {
                            EquipmentCategoryId = 3,
                            CategoryName = "Communication Device",
                            DefaultCheckoutDays = 3,
                            Description = "Radios and other communication tools"
                        });
                });

            modelBuilder.Entity("PPECheckoutSystem.Models.EquipmentItem", b =>
                {
                    b.Property<int>("EquipmentItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentItemId"));

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipmentCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("EquipmentItemId");

                    b.HasIndex("EquipmentCategoryId");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.ToTable("EquipmentItems");
                });

            modelBuilder.Entity("PPECheckoutSystem.Models.CheckoutRecord", b =>
                {
                    b.HasOne("PPECheckoutSystem.Models.Employee", "Employee")
                        .WithMany("CheckoutRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPECheckoutSystem.Models.EquipmentItem", "EquipmentItem")
                        .WithMany("CheckoutRecords")
                        .HasForeignKey("EquipmentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("EquipmentItem");
                });

            modelBuilder.Entity("PPECheckoutSystem.Models.EquipmentItem", b =>
                {
                    b.HasOne("PPECheckoutSystem.Models.EquipmentCategory", "EquipmentCategory")
                        .WithMany("EquipmentItems")
                        .HasForeignKey("EquipmentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentCategory");
                });

            modelBuilder.Entity("PPECheckoutSystem.Models.Employee", b =>
                {
                    b.Navigation("CheckoutRecords");
                });

            modelBuilder.Entity("PPECheckoutSystem.Models.EquipmentCategory", b =>
                {
                    b.Navigation("EquipmentItems");
                });

            modelBuilder.Entity("PPECheckoutSystem.Models.EquipmentItem", b =>
                {
                    b.Navigation("CheckoutRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
